### ISSUE TITLE
Microprofile Fault Tolerance examples do not deploy on 5.192

### ISSUE THREAD

**Issue by edthorne** [payara/Payara-Examples#107]
In trying to learn and apply fault tolerance features to our application, I've discovered that the example is no longer working and will not deploy.

I've tracked this down to a `NullPointerException` that is occurring at `FallbackPolicy.java` line 103. The example files are packaged in the default package and as a result the `getPackage()` method is returning `null`.

I've opened this issue here as it's trivial to fix the example by moving the classes into a non-default package. However, I'm not 100% certain that this isn't an issue that should be fixed in `FallbackPolicy.java`. As such, I'm starting the process here for discussion. If necessary, a defect can be opened on the platform and this one closed.

Another discrepancy I discovered is that the examples, while configured to run against 5.192, are still using microprofile 2.1 in the top level `pom.xml`.

**Comment by jbee** [comment]
Thanks @edthorne . The NPE definitely should be addressed. Have to check the version discrepancy.

**Comment by edthorne** [comment]
[Created #4174](https://github.com/payara/Payara/issues/4174)

**Comment by OndroMih** [comment]
The problem is solved in 5.193 - https://github.com/payara/Payara/issues/4174. The example app deploys correctly.
