### ISSUE TITLE
Is there an example of ...?

### ISSUE THREAD

**Issue by dxxvi** [payara/Payara-Examples#18]
I'd like to see an example using an embedded Payara with some resources already configured (e.g. a data source for an in-memory H2 database, a jms queue or topic) and it should be able to serve some static html pages.

**Comment by smillidge** [comment]
Thanks for the suggestion we will see what we can do

**Comment by smillidge** [comment]
Just added a Datasource example for Payara Micro where the datasource is defined in the web.xml and referenced in a servlet https://github.com/payara/Payara-Examples/tree/master/Payara-Micro/datasource-example
