### ISSUE TITLE
Problem with Payara Micro examples <parent> - Could not find artifact

### ISSUE THREAD

**Issue by blaz1** [payara/Payara-Examples#34]
When checkouting any of the projects in [payara micro examples folder](https://github.com/payara/Payara-Examples/tree/f761315644123f90abbacc15ecfe84711f11fd6e/Payara-Micro) I get the following exception:

`Project build error: Non-resolvable parent POM for fish.payara.examples.payaramicro:uber-jar-example:[unknown-version]: Could not find artifact fish.payara.examples.payaramicro:Payara-Micro:pom:1.0-SNAPSHOT in nexus ([URL excluded]) and 'parent.relativePath' points at wrong local POM @ line 4, column 13`

Is the mentioned parent POM perhaps on some internal Payara maven repo? I could not find it anywhere on google.

I tried following projects:

- jpa-datasource-example
- payara-micro-examples
- simplest-bootstrap
- uber-jar-example

**Comment by mulderbaba** [comment]
can you clone the Payara-Examples (https://github.com/payara/Payara-Examples.git) since Payara-Micro projects has a parent pom dependency to it?

**Comment by blaz1** [comment]
@mulderbaba it works now. thank you!
