### ISSUE TITLE
Test fails

### ISSUE THREAD

**Issue by RaZv** [payara/Payara-Examples#39]
hi there,
I am trying to run the test PersonDaoTest in the arquillian example project with ibm jdk 1.8 and it fails with:
Caused by: com.sun.appserv.connectors.internal.api.ConnectorRuntimeException: Invalid resource : jdbc/payaraEmbedded__pm
	at org.glassfish.jdbcruntime.service.JdbcDataSource.validateResource(JdbcDataSource.java:81)
	at org.glassfish.jdbcruntime.service.JdbcDataSource.setResourceInfo(JdbcDataSource.java:62)
	at org.glassfish.jdbcruntime.JdbcRuntimeExtension.lookupDataSourceInDAS(JdbcRuntimeExtension.java:136)
	at com.sun.enterprise.connectors.ConnectorRuntime.lookupDataSourceInDAS(ConnectorRuntime.java:589)

**Comment by smillidge** [comment]
Which test?

**Comment by RaZv** [comment]
sorry, I have updated my comment above with the name of the test and the project.
cheers,

**Comment by smillidge** [comment]
You could try chaning the payara embedded dependency to http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22payara-blue-embedded-all%22 as Payara Blue targets IBM JDK.

**Comment by RaZv** [comment]
i got the same error ... is there somewhere an working example with Arquillian? thank you

**Comment by smillidge** [comment]
@mulderbaba any ideas?

**Comment by mulderbaba** [comment]
@RaZv are you trying to execute the test within IDE or through maven build? if the latter can you provide the output in an attachment please? The payara embedded is the jndi name for jdbc resource and it's defined in glassfish-resources.xml. The way of defining that resources.xml differs from IDE to maven build.

**Comment by RaZv** [comment]
@mulderbaba good call, I ran the test through maven and it worked. (running it from eclipse mars does not). Maven version: 3.2.5, Java 8
Thanks for bringing light to this.

**Comment by mulderbaba** [comment]
great @RaZv, this example is not based on eclipse since it does not provide any integration for arquillian. please checkout our blog http://blog.payara.fish/using-payara-embedded-as-an-arquillian-container-inside-intellij-idea for running the test inside Intellij IDEA. they provide integration points for arquillian directly from the IDE itself.
