### ISSUE TITLE
Payara server stops at night

### ISSUE THREAD

**Issue by marchenar** [payara/Payara-Examples#59]
I have a customer that has an application running on Payara 4.1.2.172 (build 235) and a Linux Ubuntu 14.04.3. The application has been working fine for months, but recently they start to have the problem that everyday when they get to the office at morning the payara server is not running, and they need to start it again to run the application. When they leave the office at night always payara was working fine and next morning they find it stopped again, like while night something kill the process.

Reading the Payara log files it seems as nothing happens between the end of the day and in linux files I can't find anything reated with the problem

Any ideas?

**Comment by mikecroft** [comment]
Hi @marchenar that's an interesting problem! Could you raise it [over on our forum](https://groups.google.com/forum/#!forum/payara-forum) please? We monitor that more closely than this, so you we can more easily see when people are posting questions. When you post your question, it would be interesting to know whether this happens at the same time each night and what the output of running "uptime" is on the Ubuntu terminal. Thanks!

**Comment by marchenar** [comment]
I published the problem on the forum.

Today I went back payara to version 4.1.1.171.1 (build 139) to check if the problem is related to versión 172
